### ISSUE TITLE
Docs required

### ISSUE THREAD

**Issue by mattclegg** [SilverStripers/markdownfield#1]
Can you add a screenshot of what it looks like in the CMS to the readme.md?

**Comment by wernerkrauss** [comment]
Was my first thought, too ;)

**Comment by fonsekaean** [comment]
Hello @mattclegg @wernerkrauss 

Sorry it took me more than 2 years to sort this out. We;ve been using this internally but yeah, now that I am working on actually managing this module. And to support is to SilverStripe 4. As we are going to use this for most of our production sites. 

I've updated the readme to get it basically running on a SilverStripe 4 instance.
