### ISSUE TITLE
I'm running in to the error below, any clue?

### ISSUE THREAD

**Issue by Firesphere** [SilverStripers/markdownfield#12]
I have enabled to have Content always be a MarkDown Field, and get this error (I will investigate further later on, not really have time right now.)

Call to a member function getAttributes() on string in /vagrant/website/vendor/silverstripers/silverstripe-markdown/src/forms/MarkdownEditorField.php on line 64

**Comment by fonsekaean** [comment]
Hey @Firesphere I will check this out

**Comment by fonsekaean** [comment]
that was easy to find. Here is a fix. https://github.com/SilverStripers/markdownfield/tree/hotfix/type-errors-on-get_active

**Comment by Firesphere** [comment]
👍 I would've dug in to it myself if I had the time at the time of making the issue. Thanks!
