### ISSUE TITLE
Error TypeError: window.InsertEmbedModal is undefined [Learn More]

### ISSUE THREAD

**Issue by Firesphere** [SilverStripers/markdownfield#6]
The javascript that's loaded in for SilverStripe 4 seems to not working anymore with the latest beta

**Comment by Firesphere** [comment]
Basically, both modals are broken :(

**Comment by fonsekaean** [comment]
Hello Simon, 

Thanks for reporting that yeah I only tested it up to beta 3. Will soon fix this one up and add it to the next release

Nivanka

**Comment by fonsekaean** [comment]
Thanks  @Firesphere again for reporting this. The issues are being sorted now on the tag / release 2.0.0-beta2. And a few more modifications to the module.

**Comment by Firesphere** [comment]
👍
